import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Sidebar
    inventoryManagement: 'Inventory Management',
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    locations: 'Locations',
    salesPOS: 'Sales (POS)',
    transfers: 'Transfers',
    reports: 'Reports',
    scan: 'Scan',

    // Header
    logout: 'Logout',

    // Dashboard
    totalProducts: 'Total Products',
    totalLocations: 'Total Locations',
    todaySales: "Today's Sales",
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    recentActivity: 'Recent Activity',

    // Products Page
    addProduct: '+ Add Product',
    downloadQuotation: 'Download Quotation',
    searchByNameBarcode: 'Search by name, barcode...',
    allCategories: 'All Categories',
    singingBowl: 'Singing Bowl',
    thanka: 'Thanka',
    thankaLocket: 'Thanka Locket',
    jewelleries: 'Jewelleries',
    other: 'Other',
    image: 'Image',
    name: 'Name',
    barcode: 'Barcode',
    weight: 'Weight',
    size: 'Size',
    cost: 'Cost',
    wholesale: 'Wholesale',
    retail: 'Retail',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    noProductsFound: 'No products found. Click "Add Product" to get started.',
    addNewProduct: 'Add New Product',
    addManually: 'Add Manually',
    fillByHand: 'Fill in product details by hand',
    scanBarcode: 'Scan Barcode',
    useScanner: 'Use USB/Bluetooth barcode scanner',
    cancel: 'Cancel',
    category: 'Category',
    selectCategory: 'Select category',
    description: 'Description',
    costPrice: 'Cost Price',
    retailPrice: 'Retail Price',
    wholesalePrice: 'Wholesale Price',
    create: 'Create',
    update: 'Update',
    barcodePrefilled: 'Barcode pre-filled',
    productAlreadyExists: 'Product Already Exists',
    doYouWantToAddAgain: 'Do you want to add {name} again?',
    quantity: 'Quantity',
    addStock: 'Add Stock',
    deleteProduct: 'Delete Product',
    deleteConfirm: 'Are you sure you want to delete {name}?',
    chooseHowToAdd: "Choose how you'd like to add a product",
    whichQuotation: 'Which product quotation do you want to download?',
    priceList: 'Price List',
    costPriceList: 'Cost Price List',
    retailPriceList: 'Retail Price List',
    wholesalePriceList: 'Wholesale Price List',
    downloadExcel: 'Download Excel',

    // Common form/UI
    typeToFilter: 'Type to filter...',
    waitingForScan: 'Waiting for scan...',
    detectedBarcode: 'Detected barcode',
    uploadBarcode: 'Upload a photo of barcode or QR code',
    scanDevice: 'Scan Device',
    uploadImage: 'Upload Image',
    noLocationsFound: 'No locations found',
    nameRequired: 'Name *',
    source: 'Source',
    destination: 'Destination',
    removeFromCart: 'Remove from cart',

    // Inventory Page
    stockIn: '+ Stock In',
    allLocations: 'All Locations',
    product: 'Product',
    location: 'Location',
    status: 'Status',
    inStock: 'In Stock',
    lowStockLabel: 'Low Stock',
    outOfStockLabel: 'Out of Stock',
    manage: 'Manage',
    manageQuantity: 'Manage Quantity',
    noInventoryRecords: 'No inventory records. Use "Stock In" to add stock.',
    selectProduct: 'Select product',
    selectLocation: 'Select location',

    // Transfers Page
    transferCheckout: 'Transfer / Checkout',
    stockOutFrom: 'Stock Out From',
    stockInTo: 'Stock In To',
    selectSourceLocation: 'Select source location',
    selectDestinationLocation: 'Select destination location',
    defaultLocation: 'Default Location',
    type: 'Type',
    transferCart: 'Transfer Cart',
    addItem: '+ Add Item',
    addMultiple: '+ Add Multiple',
    noItemsInCart: 'No items in cart. Use your barcode scanner or add products manually.',
    available: 'Available',
    transferQty: 'Transfer Qty',
    transferLocation: 'Transfer Location',
    overStock: 'Over Stock',
    confirmTransfer: 'Confirm Transfer',
    processing: 'Processing...',
    totalItems: 'total items',
    addItemToCart: 'Add Item to Cart',
    addToCart: 'Add to Cart',
    availableAt: 'Available at {location}',
    alreadyTransferred: 'Already Transferred',
    alreadyInCart: '{name} is already in the cart. Do you want to transfer more?',
    quantityToAdd: 'Quantity to add',
    transferMore: 'Transfer More',
    selectTransferLocations: 'Select Transfer Locations',
    selectLocationsBeforeScan: 'Please select both locations before scanning products.',
    scannedBarcode: 'Scanned barcode',
    confirmContinue: 'Confirm & Continue',
    multiScanMode: 'Multi-Scan Mode',
    keepScanning: 'Keep scanning barcodes to add products to the cart continuously.',
    scanLog: 'Scan Log',
    added: 'added',
    waitingForScans: 'Waiting for scans...',
    productNotFound: 'Product not found',
    doneScanning: 'Done Scanning',
    productDoesntExist: "Product Doesn't Exist",
    noProductWithBarcode: 'No product found with barcode:',
    productCreated: 'Product created! Scan again to add it to the cart.',
    recentTransfers: 'Recent Transfers',
    transferRecords: 'Transfer Records',
    whichLocationRecords: 'Which location do you want the transfer records for?',
    viewRecords: 'View Records',
    stockOut: 'Stock Out',
    stockInLabel: 'Stock In',
    transferredQty: 'Transferred Qty',
    date: 'Date',
    noTransfersYet: 'No transfers yet',

    // Sales Page
    pointOfSale: 'Point of Sale',
    scanEnterBarcode: 'Scan / Enter Barcode',
    scanOrType: 'Scan barcode or type and press Enter',
    or: 'or',
    chooseProduct: 'Choose a product...',
    priceType: 'Price Type',
    total: 'Total',
    completeSale: 'Complete Sale',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    clearCart: 'Clear Cart',
    confirmPayment: 'Confirm Payment',
    emptyCart: 'Cart is empty',
    scanToAdd: 'Scan a barcode or select a product to add items',
    itemAdded: 'Item added to cart',
    items: 'items',
    manualSale: 'Manual Sale',
    searchProducts: 'Search products...',
    scanBarcodeDesc: 'Use USB/Bluetooth barcode scanner to add products',
    manualSaleDesc: 'Search and select products manually',
    productName: 'Product Name',
    remove: 'Remove',
    salesFrom: 'Sales From',

    // Locations Page
    addLocation: '+ Add Location',
    editLocation: 'Edit Location',
    addNewLocation: 'Add New Location',
    locationName: 'Location Name',
    locationType: 'Location Type',
    warehouse: 'Warehouse',
    shop: 'Shop',
    exhibition: 'Exhibition',
    noLocationsYet: 'No locations yet. Click "Add Location" to get started.',
    deleteLocationConfirm: 'Are you sure you want to delete this location?',

    // Reports Page
    exportExcel: 'Export Excel',
    allProducts: 'All Products',
    filter: 'Filter',
    fromDate: 'From Date',
    toDate: 'To Date',
    all: 'All',
    sale: 'Sale',
    transfer: 'Transfer',
    from: 'From',
    to: 'To',
    by: 'By',
    noTransactionsFound: 'No transactions found',

    // Dashboard
    recentTransactionsTitle: 'Recent Transactions',

    // Scan Page
    barcodeScanner: 'Barcode Scanner',
    cameraScanner: 'Camera Scanner',
    enterBarcodeManually: 'Or enter barcode manually',
    typeBarcodeEnter: 'Type barcode and press Enter',
    productInfo: 'Product Info',
    stockLevels: 'Stock Levels',
    noStockRecords: 'No stock records for this product',
    scanBarcodeToSee: 'Scan a barcode or enter one manually to see product details',
    units: 'units',
  },
  cn: {
    // Sidebar
    inventoryManagement: '库存管理',
    dashboard: '仪表板',
    products: '产品',
    inventory: '库存',
    locations: '位置',
    salesPOS: '销售 (POS)',
    transfers: '转移',
    reports: '报告',
    scan: '扫描',

    // Header
    logout: '退出',

    // Dashboard
    totalProducts: '产品总数',
    totalLocations: '位置总数',
    todaySales: '今日销售',
    lowStock: '库存不足',
    outOfStock: '缺货',
    recentActivity: '最近活动',

    // Products Page
    addProduct: '+ 添加产品',
    downloadQuotation: '下载报价单',
    searchByNameBarcode: '按名称、条码搜索...',
    allCategories: '所有类别',
    singingBowl: '颂钵',
    thanka: '唐卡',
    thankaLocket: '唐卡吊坠',
    jewelleries: '珠宝',
    other: '其他',
    image: '图片',
    name: '名称',
    barcode: '条码',
    weight: '重量',
    size: '尺寸',
    cost: '成本',
    wholesale: '批发',
    retail: '零售',
    actions: '操作',
    edit: '编辑',
    delete: '删除',
    noProductsFound: '未找到产品。点击"添加产品"开始。',
    addNewProduct: '添加新产品',
    addManually: '手动添加',
    fillByHand: '手动填写产品详情',
    scanBarcode: '扫描条码',
    useScanner: '使用USB/蓝牙条码扫描器',
    cancel: '取消',
    category: '类别',
    selectCategory: '选择类别',
    description: '描述',
    costPrice: '成本价',
    retailPrice: '零售价',
    wholesalePrice: '批发价',
    create: '创建',
    update: '更新',
    barcodePrefilled: '条码已预填',
    productAlreadyExists: '产品已存在',
    doYouWantToAddAgain: '您要再次添加 {name} 吗？',
    quantity: '数量',
    addStock: '添加库存',
    deleteProduct: '删除产品',
    deleteConfirm: '您确定要删除 {name} 吗？',
    chooseHowToAdd: '选择添加产品的方式',
    whichQuotation: '您要下载哪个产品报价单？',
    priceList: '价格表',
    costPriceList: '成本价格表',
    retailPriceList: '零售价格表',
    wholesalePriceList: '批发价格表',
    downloadExcel: '下载 Excel',

    // Common form/UI
    typeToFilter: '输入筛选...',
    waitingForScan: '等待扫描...',
    detectedBarcode: '检测到条码',
    uploadBarcode: '上传条码或二维码照片',
    scanDevice: '扫描设备',
    uploadImage: '上传图片',
    noLocationsFound: '未找到位置',
    nameRequired: '名称 *',
    source: '来源',
    destination: '目的',
    removeFromCart: '从购物车移除',

    // Inventory Page
    stockIn: '+ 入库',
    allLocations: '所有位置',
    product: '产品',
    location: '位置',
    status: '状态',
    inStock: '有库存',
    lowStockLabel: '库存不足',
    outOfStockLabel: '缺货',
    manage: '管理',
    manageQuantity: '管理数量',
    noInventoryRecords: '没有库存记录。使用"入库"添加库存。',
    selectProduct: '选择产品',
    selectLocation: '选择位置',

    // Transfers Page
    transferCheckout: '转移 / 结账',
    stockOutFrom: '出库来源',
    stockInTo: '入库目的',
    selectSourceLocation: '选择来源位置',
    selectDestinationLocation: '选择目的位置',
    defaultLocation: '默认位置',
    type: '类型',
    transferCart: '转移购物车',
    addItem: '+ 添加项目',
    addMultiple: '+ 批量添加',
    noItemsInCart: '购物车为空。使用条码扫描器或手动添加产品。',
    available: '可用',
    transferQty: '转移数量',
    transferLocation: '转移位置',
    overStock: '超出库存',
    confirmTransfer: '确认转移',
    processing: '处理中...',
    totalItems: '总件数',
    addItemToCart: '添加到购物车',
    addToCart: '加入购物车',
    availableAt: '在 {location} 可用',
    alreadyTransferred: '已转移',
    alreadyInCart: '{name} 已在购物车中。您要转移更多吗？',
    quantityToAdd: '添加数量',
    transferMore: '转移更多',
    selectTransferLocations: '选择转移位置',
    selectLocationsBeforeScan: '扫描产品前请选择两个位置。',
    scannedBarcode: '已扫描条码',
    confirmContinue: '确认并继续',
    multiScanMode: '批量扫描模式',
    keepScanning: '持续扫描条码以连续添加产品到购物车。',
    scanLog: '扫描记录',
    added: '已添加',
    waitingForScans: '等待扫描...',
    productNotFound: '未找到产品',
    doneScanning: '完成扫描',
    productDoesntExist: '产品不存在',
    noProductWithBarcode: '未找到条码对应的产品：',
    productCreated: '产品已创建！再次扫描以添加到购物车。',
    recentTransfers: '最近转移',
    transferRecords: '转移记录',
    whichLocationRecords: '您要查看哪个位置的转移记录？',
    viewRecords: '查看记录',
    stockOut: '出库',
    stockInLabel: '入库',
    transferredQty: '转移数量',
    date: '日期',
    noTransfersYet: '暂无转移记录',

    // Sales Page
    pointOfSale: '销售点',
    scanEnterBarcode: '扫描 / 输入条码',
    scanOrType: '扫描条码或输入后按回车',
    or: '或',
    chooseProduct: '选择产品...',
    priceType: '价格类型',
    total: '总计',
    completeSale: '完成销售',
    orderSummary: '订单摘要',
    subtotal: '小计',
    qty: '数量',
    unitPrice: '单价',
    clearCart: '清空购物车',
    confirmPayment: '确认付款',
    emptyCart: '购物车为空',
    scanToAdd: '扫描条码或选择产品以添加商品',
    itemAdded: '已添加到购物车',
    items: '件商品',
    manualSale: '手动销售',
    searchProducts: '搜索产品...',
    scanBarcodeDesc: '使用USB/蓝牙条码扫描器添加产品',
    manualSaleDesc: '手动搜索和选择产品',
    productName: '产品名称',
    remove: '移除',
    salesFrom: '销售地点',

    // Locations Page
    addLocation: '+ 添加位置',
    editLocation: '编辑位置',
    addNewLocation: '添加新位置',
    locationName: '位置名称',
    locationType: '位置类型',
    warehouse: '仓库',
    shop: '商店',
    exhibition: '展览',
    noLocationsYet: '暂无位置。点击"添加位置"开始。',
    deleteLocationConfirm: '您确定要删除此位置吗？',

    // Reports Page
    exportExcel: '导出 Excel',
    allProducts: '所有产品',
    filter: '筛选',
    fromDate: '开始日期',
    toDate: '结束日期',
    all: '全部',
    sale: '销售',
    transfer: '转移',
    from: '来源',
    to: '目的',
    by: '操作人',
    noTransactionsFound: '未找到交易记录',

    // Dashboard
    recentTransactionsTitle: '最近交易',

    // Scan Page
    barcodeScanner: '条码扫描器',
    cameraScanner: '相机扫描',
    enterBarcodeManually: '或手动输入条码',
    typeBarcodeEnter: '输入条码并按回车',
    productInfo: '产品信息',
    stockLevels: '库存水平',
    noStockRecords: '此产品没有库存记录',
    scanBarcodeToSee: '扫描条码或手动输入以查看产品详情',
    units: '件',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ya_lang') || 'en');

  const toggleLang = () => {
    const next = lang === 'en' ? 'cn' : 'en';
    setLang(next);
    localStorage.setItem('ya_lang', next);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  // Translate user-entered data values (categories, location types, status, etc.)
  const dataMap = {
    en: {},
    cn: {
      // Categories
      'Singing Bowl': '颂钵',
      'Thanka': '唐卡',
      'Thanka Locket': '唐卡吊坠',
      'Jewelleries': '珠宝',
      // Location types
      'warehouse': '仓库',
      'shop': '商店',
      'exhibition': '展览',
      // Transaction types
      'stock_in': '入库',
      'stock in': '入库',
      'transfer': '转移',
      'sale': '销售',
      // Price types
      'retail': '零售',
      'wholesale': '批发',
      'cost': '成本',
      // Status
      'In Stock': '有库存',
      'Low Stock': '库存不足',
      'Out of Stock': '缺货',
      'Over Stock': '超出库存',
    },
  };
  const td = (value) => {
    if (!value) return value;
    if (lang === 'en') return value;
    return dataMap[lang]?.[value] || value;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, td }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
